#!/usr/bin/python3
# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/master/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))
import testlib

# Test with pre-recorded journal with tlog UID 981
class TestApplication(testlib.MachineCase):
    def testPlay(self):
        b = self.browser
        m = self.machine
        m.execute("cp /root/1.journal /var/log/journal/")
        self.login_and_go("/session-recording")
        b.wait_present(".content-header-extra")
        b.wait_present("#user")
        b.click(".listing-ct-item")
        b.wait_present("button.margin-right-btn:nth-child(3)")
        b.click("button.margin-right-btn:nth-child(3)")
        b.wait_timeout(15000)
        b.wait_present(".fa-pause")
        b.click("button.margin-right-btn:nth-child(3)")
        b.snapshot('play-default')
        m.execute("rm -rf /var/log/journal/1.journal")

    def testSkip(self):
        b = self.browser
        m = self.machine
        m.execute("cp /root/1.journal /var/log/journal/")
        self.login_and_go("/session-recording")
        b.wait_present(".content-header-extra")
        b.wait_present("#user")
        b.click(".listing-ct-item")
        b.wait_present("button.margin-right-btn:nth-child(3)")
        b.wait_present("button.margin-right-btn:nth-child(4)")
        b.click("button.margin-right-btn:nth-child(4)")
        b.wait_timeout(1000)
        b.wait_present("button.margin-right-btn:nth-child(4)")
        b.click("button.margin-right-btn:nth-child(4)")
        b.wait_timeout(1000)
        b.wait_present("button.margin-right-btn:nth-child(4)")
        b.click("button.margin-right-btn:nth-child(4)")
        b.wait_timeout(1000)
        b.wait_present("button.margin-right-btn:nth-child(4)")
        b.click("button.margin-right-btn:nth-child(4)")
        b.wait_timeout(1000)
        b.wait_present("button.margin-right-btn:nth-child(4)")
        b.click("button.margin-right-btn:nth-child(4)")
        b.wait_timeout(1000)
        b.snapshot('play-default')
        m.execute("rm -rf /var/log/journal/1.journal")

if __name__ == '__main__':
    testlib.test_main()
