#!/bin/sh
# image-customize script to prepare a bots VM for testing this application
# The application package will be installed separately
set -eux

# don't force https:// (self-signed cert)
mkdir -p /etc/cockpit
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if systemctl is-active -q firewalld.service; then
    firewall-cmd --add-service=cockpit --permanent
fi
systemctl enable cockpit.socket
