version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # run these when most of our developers don't work, don't DoS our CI over the day
      time: "22:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    groups:
      eslint:
        patterns:
          - "eslint*"
      esbuild:
        patterns:
          - "esbuild*"
      stylelint:
        patterns:
          - "stylelint*"
      patternfly:
        patterns:
          - "@patternfly*"
